### ISSUE TITLE
Classroom window not in force learning mode is force maximized.

### ISSUE THREAD

**Issue by QiZhengyuan** [CarlGao4/ClassIn-Mover#2]
The program always force maximize the classroom window, even if it is not in force learning mode.

**Comment by QiZhengyuan** [comment]
Problem discovered in v1.0.3.

**Comment by TimeDevBlocker** [comment]
不在专注学习模式为什么要用Classin Mover

**Comment by CarlGao4** [comment]
We have been trying different methods to identify window in `focused learning mode` from normal windows, however everything is same. We will try to add manual resizing so that you can choose whether patching the window or not.

**Comment by CarlGao4** [comment]
This has been fixed under v2.0.0
