### ISSUE TITLE
version  2.1.0 can't resize and drag to move the classroom windows

### ISSUE THREAD

**Issue by yc004** [CarlGao4/ClassIn-Mover#5]
conparied with former vervision, v2.1.0 can't let me to use mouse to drag the classin windows. Hope author can sovle the issue **: )**

**Comment by CarlGao4** [comment]
I've fixed this bug in 2.1.0.1 just now. You may have received the new version by checking updates. I accidentally removed a space in the Chinese translation so the format was destroyed.
