### ISSUE TITLE
I want to participate in the English localization of this project.

### ISSUE THREAD

**Issue by Melendez1209** [CarlGao4/ClassIn-Mover#6]
# 我希望加入到ClassIn Mover工程的英化工作，望接纳。
这不是我首次参加，开源项目的开发，此处我也用到了多语言。只是一个小项目，就没有写Json,但这次有了Json，我相信我可以做得更好，这也会让我事半功倍。我因为学业的原因，工作时间应该只有节假日😢，望见谅。
# I hope to join the English work of ClassIn Mover project. I hope you can accept it. 
This is not my first time to participate in the development of open source projects. I also use multiple languages here. Just a small project, I didn't write Json. But with Json this time, I believe I can do better, which will also make me get twice the result with half the effort. Because of my studies, I should only work on holidays 😢， I see and forgive.

[Python多语言的应用](https://github.com/Melendez1209/Python-Note/blob/main/%E8%BF%9B%E9%98%B6/%E5%AE%9E%E6%88%98/BMI%E8%AE%A1%E7%AE%97%E5%99%A8/BMI%E8%AE%A1%E7%AE%97%E5%99%A8%20v2.0Bata1.py)

**Comment by CarlGao4** [comment]
I've noticed your PR and email.
